apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-stack

labels:
  - pairs:
      app.kubernetes.io/part-of: ai-stack
      app.kubernetes.io/component: rag-pipeline

resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
